# --- Set theme --- #
remote_theme: "daattali/beautiful-jekyll@4.1.0"
plugins:
  - jekyll-remote-theme

# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://ja2-stracciatella.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Jagged Alliance 2 Stracciatella

# Short description of your site
description: This is continuation of venerable JA2-Stracciatella project. The goal of the project is to make Jagged Alliance 2 available on a wide range of platforms, improve its stability, fix bugs and provide a stable platform for mod development.

# --- Navigation bar options --- #

title-img: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Home: "/"
  News: "news"
  Features: "features"
  How to run: "how-to-run"
  Bugs: "development"
  History: "history"
  Download: "download"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author: JA2 Stracciatella Team

# Select which links to show in the footer
social-network-links:
  github: ja2-stracciatella/ja2-stracciatella
  rss: true

# Colors

link-col: "#9c2111"
hover-col: "#e79408"

# Custom styles
site-css:
  - "/css/ja2-stracciatella.css"

# --- Misc --- #

collections:
  - history

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
